version: 2
updates:
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    groups:
      python-patch-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: pip
    directory: /aibackend
    schedule:
      interval: weekly
    groups:
      python-patch-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: pip
    directory: /aimodel
    schedule:
      interval: weekly
    groups:
      python-patch-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-patch-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: cargo
    directory: /mobile/rust
    schedule:
      interval: weekly
    groups:
      rust-patch-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: pub
    directory: /mobile
    schedule:
      interval: weekly
    groups:
      flutter-patch-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: pub
    directory: /expense-helper/mobile
    schedule:
      interval: weekly
    groups:
      flutter-patch-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /aibackend
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /aimodel
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-patch-minor:
        update-types:
          - minor
          - patch